config/routes.rb
Rails.application.routes.draw do
	#get "/candidates", to: "candidates#index"
	#get "/candidates/new", to: "candidates#new"

	#resourses :users, only: [:index] #(只要index一條路徑就好)

	resources :candidates do
		#collection do #(擴充功能)
			##candidates/list => 
			#get :list, to: "candidates#list"
			##candidates/all
		#end

		#member
			##candidates/2/vote
			##candidate/2/cancel
		member do
			post :vote, to: "candidates#vote"
		end

	end

	#post "/candidates/:id/vote", to: "candidates#vote"

	# resources :users do
	# 	resources :posts, only: [:index, :create, :new]
	# end
	# resources :post , only: [:show, :edit, :update, :destroy]	
	# ====>
	# resources :users do
	# 	resources :posts, shallow:true
	# end




end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/candidate.rb
class Candidate < ApplicationRecord
	has_many :vote_logs
	validates :name, presence: true
end

app/models/vote_log.rb
class VoteLog < ApplicationRecord
  belongs_to :candidate, counter_cache: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/candidates_controller.rb
class CandidatesController < ApplicationController

	before_action :find_cand, only: [:show, :edit, :update, :destroy, :vote]
	
	def index
		@candidates = Candidate.all.order(id: :desc)
		#render action: "edit" #去找edit.html
	end

	def new
		@candidate = Candidate.new
	end
	def create
		@candidate = Candidate.new(clean_cand_params) 

      if @candidate.save
        redirect_to candidates_path, notice: "new!"
      else
        render :new, notice: "WRONG!"
        #redirect_to new_candidate_path 
        #用redirect_to 不會保留剛剛打好的資料 會惹怒民眾！  (edit同理
      end
	end

	def edit
		#find_cand
	end

	def update
		#find_cand

		if @candidate.update(clean_cand_params)
			redirect_to candidates_path, notice: "update!"
    else
        render :edit, notice: "WRONG!"
    end
	end

	def destroy
		#find_cand
		@candidate.destroy
		redirect_to candidates_path, notice: "destroy!"
	end
	def show
		#find_cand
	end

	def vote

		@candidate.vote_logs.create(ip_address: request.remote_ip) # 包含save!
		#@candidate.vote_logs.new(ip_address: remote_ip)
		# @candidate.save

		#MAIL
		CandidateMailer.notify(@candidates).deliver

		redirect_to candidates_path, notice: "vote!"

		# @candidate.vote += 1
		# @candidate.save
		# redirect_to candidates_path, notice: "vote!"
	end
		
	


	private #######

	def clean_cand_params #params[:candidate]
		clean_params = params.require(:candidate).permit(:name, :age, :gender, :politics)
	end

	def find_cand
		@candidate = Candidate.find_by(id: params[:id])
		redirect_to candidates_path unless @candidate
	end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/candidates_helper.rb
module CandidatesHelper

	def gender_p(value)
		if value == 1
			"M"
		elsif value == 2
			"F"
		else
			"unknown"
		end
	end
end

app/views/candidates/_candidate.html.erb
<tr>

<td> <%= link_to "投！", vote_candidate_path(candidate), method: "post", data: {confirm: "sure?"}, class:"btn btn-success" %></td>
<td> <%= candidate.name %></td>
<td> <%= candidate.age %> / <%= gender_p(candidate.gender) %></td>
<td> <%= candidate.politics %></td>
<td> <%= candidate.vote_logs.size %></td>
<td> <%= link_to "edit", edit_candidate_path(candidate), class:"btn btn-warning"%></td>

<td> <%= link_to "show", candidate_path(candidate), class:"btn btn-default" %></td>
<td> <%= link_to "destroy", candidate_path(candidate) , method: "delete", data: { confirm: "sure?" }, class:"btn btn-danger" %></td>


</tr>

app/views/candidates/_form.html.erb
	<%= form_for candidate do |f| %>

  <%= f.label :name, "姓名" %>
  <%= f.text_field :name %> <br />

 	<%= f.label :age, "年齡" %>
  <%= f.text_field :age %> <br /> 

  <%= f.label :gender, "性別" %>
  <%= f.text_field :gender %> <br />

  <%= f.label :politics, "政見" %>
  <%= f.text_area :politics %> <br />

  <%= f.submit class:"btn btn-warning" %>


<%= link_to 'back', candidates_path, class:"btn btn-info"%>
	
<% end %>

app/views/candidates/edit.html.erb
<h1>edit</h1>

<%= render "form", candidate: @candidate %>

app/views/candidates/index.html.erb
<h1>List</h1>

<%= link_to "new", new_candidate_path, class:"btn btn-info" %>

  <table class="table">
    <thead>
      <tr>
        <td>vote !</td>
        <td>name</td>
        <td>age / gender</td>
        <td>politics</td>
        <td>vote-num</td>
        <td>tool</td>
      </tr>
    </thead>
    <tbody>

     <%= render partial: "candidate", collection: @candidates %>

    </tbody>
  </table>

app/views/candidates/new.html.erb
<h1>new</h1>

<%= render "form", candidate: @candidate %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>MyVote</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
  <div class="container">
  <%= flash[:notice] %>
  	<%= yield %>
  </div>
    
  </body>
</html>